#!/bin/sh

# SPDX-License-Identifier: BSD-2-Clause
#
#  Copyright (c) 2009 Douglas Barton
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
#  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
#  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
#  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
#  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
#  OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
#  SUCH DAMAGE.
#
#  Geovanni B.R. (geobarrod) <igeo.cu@gmail.com>, 2026-01-05
#  Improvements to the original `service(8)` command to allow multiple services
#  management in a single invocation. Supported actions include:
#  `start`, `stop`, `restart`, `status`, `rcvar`, `describe`, `onestart`,
#   `onestop`, `onerestart`, `onestatus`, `reload`, `enable`, `disable`.

. /etc/rc.subr
load_rc_config

usage () {
    echo ''
    echo 'Usage:'
    echo "${0##*/} [-j <jail name or id>] -e"
    echo "${0##*/} [-j <jail name or id>] [-q] -R"
    echo "${0##*/} [-j <jail name or id>] [-v] -l"
    echo "${0##*/} [-j <jail name or id>] [-v] -r"
    echo "${0##*/} [-dqv] [-E var=value] <rc.d script> start|stop|etc."
    echo "${0##*/} <action> <service1> [service2 ...]"
    echo "${0##*/} -h"
    echo ''
    echo "-d                Enable debugging of rc.d scripts"
    echo "-j                Perform actions within the named jail"
    echo "-E n=val          Set variable n to val before executing the rc.d script"
    echo "-e                Show services that are enabled"
    echo "-R                Stop and start enabled $local_startup services"
    echo "-l                List all scripts in /etc/rc.d and $local_startup"
    echo "-r                Show the results of boot time rcorder"
    echo "-q                Quiet"
    echo "-v                Verbose"
    echo ''
}

while getopts 'dE:ehj:lqrRv' COMMAND_LINE_ARGUMENT ; do
    case "${COMMAND_LINE_ARGUMENT}" in
    d)  DEBUG=dopt ;;
    E)  VARS="${VARS} ${OPTARG}" ;;
    e)  ENABLED=eopt ;;
    h)  usage ; exit 0 ;;
    j)  JAIL="${OPTARG}" ;;
    l)  LIST=lopt ;;
    q)  QUIET=qopt ;;
    r)  RCORDER=ropt ;;
    R)  RESTART=Ropt ;;
    v)  VERBOSE=vopt ;;
    *)  usage ; exit 1 ;;
    esac
done
shift $(( $OPTIND - 1 ))

if [ -n "${JAIL}" ]; then
    args=""
    [ -n "${ENABLED}" ] && args="${args} -e"
    [ -n "${LIST}" ] && args="${args} -l"
    [ -n "${QUIET}" ] && args="${args} -q"
    [ -n "${RCORDER}" ] && args="${args} -r"
    [ -n "${RESTART}" ] && args="${args} -R"
    [ -n "${VERBOSE}" ] && args="${args} -v"
    for var in ${VARS}; do
        args="${args} -E ${var}"
    done
    /usr/sbin/jexec -l "${JAIL}" /usr/sbin/service $args "$@"
    exit $?
fi

if [ -n "$DEBUG" ]; then
    VARS="${VARS} rc_debug=yes"
fi

# --- main logic for multiple services ---

if [ $# -lt 1 ]; then
    usage
    exit 1
fi

first=$1
shift

actions="start stop restart status rcvar describe onestart onestop onerestart onestatus reload enable disable"

is_action=0
for a in $actions; do
    if [ "$first" = "$a" ]; then
        is_action=1
        break
    fi
done

if [ $is_action -eq 1 ]; then
    # New syntax: action first, then multiple services
    action=$first
    if [ $# -lt 1 ]; then
        echo "No services specified"
        exit 1
    fi
    for script in "$@"; do
        if [ "$action" = "enable" ]; then
            echo "Enabling $script in rc.conf"
            sysrc "${script}_enable=YES"
            continue
        elif [ "$action" = "disable" ]; then
            echo "Disabling $script in rc.conf"
            sysrc "${script}_enable=NO"
            continue
        fi
        found=0
        for dir in /etc/rc.d $local_startup; do
            if [ -x "$dir/$script" ]; then
                [ -n "$VERBOSE" ] && echo "$script is located in $dir"
                if [ -n "$QUIET" ]; then
                    /usr/bin/env -i -L -/daemon HOME=/ PATH=/sbin:/bin:/usr/sbin:/usr/bin ${VARS} "$dir/$script" "$action" > /dev/null 2>&1
                else
                    /usr/bin/env -i -L -/daemon HOME=/ PATH=/sbin:/bin:/usr/sbin:/usr/bin ${VARS} "$dir/$script" "$action"
                fi
                found=1
                break
            fi
        done
        if [ $found -eq 0 ]; then
            echo "$script does not exist in /etc/rc.d or the local startup directories (${local_startup}), or is not executable"
        fi
    done
else
    # Classic syntax: service first, then action
    script=$first
    if [ $# -lt 1 ]; then
        usage
        exit 1
    fi
    action=$1
    shift
    if [ "$action" = "enable" ]; then
        echo "Enabling $script in rc.conf"
        sysrc "${script}_enable=YES"
        exit 0
    elif [ "$action" = "disable" ]; then
        echo "Disabling $script in rc.conf"
        sysrc "${script}_enable=NO"
        exit 0
    fi
    for dir in /etc/rc.d $local_startup; do
        if [ -x "$dir/$script" ]; then
            [ -n "$VERBOSE" ] && echo "$script is located in $dir"
            if [ -n "$QUIET" ]; then
                exec /usr/bin/env -i -L -/daemon HOME=/ PATH=/sbin:/bin:/usr/sbin:/usr/bin ${VARS} "$dir/$script" "$action" "$@" > /dev/null 2>&1
            else
                exec /usr/bin/env -i -L -/daemon HOME=/ PATH=/sbin:/bin:/usr/sbin:/usr/bin ${VARS} "$dir/$script" "$action" "$@"
            fi
        fi
    done
    echo "$script does not exist in /etc/rc.d or the local startup directories (${local_startup}), or is not executable"
    exit 1
fi
